PROJETO/Agenda/Agenda/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Agenda.Models;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;

namespace Agenda.Controllers
{
    public class CategoriaController : Controller
    {

        public ActionResult Index()
        {
            using (AgendaContext agendaContext = new AgendaContext())
            {
                List<Categoria> categorias = agendaContext.categorias.ToList();
                return View( categorias );
            }
        }

        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Incluir(Categoria categoria)
        {
            // Utilizando procedure
            string connectionString = ConfigurationManager.ConnectionStrings["AgendaContext"].ConnectionString;

            try
            {
                using (SqlConnection con = new SqlConnection( connectionString ))
                {
                    SqlCommand cmd = new SqlCommand( "sp_InserirCategoria", con );
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlParameter sqlParameterNome = new SqlParameter() { SqlValue = categoria.CategoriaNome, ParameterName = "@CategoriaNome" };

                    cmd.Parameters.Add( sqlParameterNome );

                    con.Open();
                    cmd.ExecuteNonQuery();
                }
                return RedirectToAction( "Index" );

            }
            catch
            {
                ViewBag.Error = "Impossivel incluir!";
                return View();
            }
        }

        [HttpPost]
        [ActionName( "Excluir" )]
        public string Excluir(int id)
        {
            using (AgendaContext agendaContext = new AgendaContext())
            {
                Categoria categoria = agendaContext.categorias.Single(cat => cat.CategoriaId == id);
                agendaContext.categorias.Remove( categoria );
                try
                {
                    agendaContext.SaveChanges();
                    return "Excluida com sucesso!";
                }
                catch
                {
                    return "Erro ao tentar excluir!";
                }
            }

        }
        
        [HttpPost]
        [ActionName("_ListarCategoria")]
        public ActionResult _ListarCategoria()
        {
            using (AgendaContext agendaContext = new AgendaContext())
            {
                List<Categoria> categorias = agendaContext.categorias.ToList();
                return View( categorias );
            }
        }
    }
}

PROJETO/Agenda/Agenda/Controllers/EventoController.cs
using Agenda.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agenda.Controllers
{
    public class EventoController : Controller
    {
        private static DateTime dataIni = DateTime.Today;
        private static DateTime dataFim = DateTime.Today.AddDays( 1 );

        public ActionResult Index()
        {
            dataIni = DateTime.Today;
            dataFim = DateTime.Today.AddDays( 1 );
            using (AgendaContext agendaContext = new AgendaContext())
            {
                List<Evento> eventos = agendaContext.eventos.ToList();
                return View( eventos );
            }
        }

        public ActionResult Incluir()
        {
            CarregarCategorias();
            return View();
        }

        [HttpPost]
        /**Verificar*/
        public ActionResult Incluir(Evento evento)
        {
            CarregarCategorias();
            // Utilizando procedure
            string connectionString = ConfigurationManager.ConnectionStrings["AgendaContext"].ConnectionString;

            try
            {
                using (SqlConnection con = new SqlConnection( connectionString ))
                {
                    SqlCommand cmd = new SqlCommand( "sp_InserirEvento", con );
                    cmd.CommandType = CommandType.StoredProcedure;
                    SqlParameter sqlParameterNome = new SqlParameter() { SqlValue = evento.EventoNome, ParameterName = "@EventoNome" };
                    SqlParameter sqlParameterDescricao = new SqlParameter() { SqlValue = evento.EventoDescricao, ParameterName = "@Eventodescricao" };
                    SqlParameter sqlParameterDataIni = new SqlParameter() { SqlValue = evento.EventoDataInicio, ParameterName = "@EventoDataInicio" };
                    SqlParameter sqlParameterDataFim = new SqlParameter() { SqlValue = evento.EventoDataFim, ParameterName = "@EventoDataFim" };
                    SqlParameter sqlParameterStatus = new SqlParameter() { SqlValue = evento.EventoStatus, ParameterName = "@EventoStatus" };
                    SqlParameter sqlParameterCategoria = new SqlParameter() { SqlValue = evento.CategoriaId, ParameterName = "@CategoriaId" };

                    cmd.Parameters.Add( sqlParameterNome );
                    cmd.Parameters.Add( sqlParameterDescricao );
                    cmd.Parameters.Add( sqlParameterDataIni );
                    cmd.Parameters.Add( sqlParameterDataFim );
                    cmd.Parameters.Add( sqlParameterStatus );
                    cmd.Parameters.Add( sqlParameterCategoria );

                    con.Open();
                    cmd.ExecuteNonQuery();
                }
                return RedirectToAction( "Index" );

            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }
        }

        [HttpPost]
        [ActionName( "Excluir" )]
        public string Excluir(int id)
        {
            using (AgendaContext agendaContext = new AgendaContext())
            {
                Evento evento = agendaContext.eventos.Single( eve => eve.EventoId == id );
                agendaContext.eventos.Remove( evento );
                try
                {
                    agendaContext.SaveChanges();
                    return "Sucesso";
                }
                catch
                {
                    return "Impossivel excluir!";
                }
            }
        }

        [HttpPost]
        [ActionName( "_ListarEventos" )]
        public ActionResult _ListarEventos()
        {
            return View( GetEventos() );
        }

        private List<Evento> GetEventos()
        {
            using (AgendaContext agendaContext = new AgendaContext())
            {
                return agendaContext.eventos.ToList().Where( eve => eve.EventoDataInicio > dataIni && eve.EventoDataFim < dataFim ).ToList();
            }
        }

        private void CarregarCategorias()
        {
            List<Categoria> categorias = new List<Categoria>();
            using (AgendaContext agendaContext = new AgendaContext())
            {
                categorias = agendaContext.categorias.ToList();
                ViewBag.Categorias = categorias;
            }

        }

        [HttpPost]
        [ActionName( "TestarDatas" )]
        public string TestarDatas(string dateTimeInicio, string dateTimeFim)
        {
            try
            {
                DateTime dateTimeI = Convert.ToDateTime( dateTimeInicio );
                DateTime dateTimeF = Convert.ToDateTime( dateTimeFim );
                int res = dateTimeF.CompareTo( dateTimeI );
                if (res == -1)
                {
                    return "Da inicial deve ser menor que data final.";

                }
                dataIni = dateTimeI;
                dataFim = dateTimeF;
                return "";
            }
            catch
            {
                return "Impossivel converter datas";
            }
        }

        [HttpPost]
        [ActionName( "Finalizar" )]
        public string Finalizar(int id)
        {
            using (AgendaContext agendaContext = new AgendaContext())
            {
                Evento evento = agendaContext.eventos.Single(eve => eve.EventoId == id);
                evento.EventoStatus = "F";
                try
                {
                    agendaContext.SaveChanges();
                    return "Finalizado com sucesso";
                }
                catch
                {
                    return "Não foi possivel finalizar!";
                }
            }
            //string connectionString = ConfigurationManager.ConnectionStrings["AgendaContext"].ConnectionString;
            //try
            //{
            //    using (SqlConnection con = new SqlConnection( connectionString ))
            //    {
            //        SqlCommand cmd = new SqlCommand( "sp_FecharEvento", con );
            //        cmd.CommandType = CommandType.StoredProcedure;
            //        cmd.Parameters.Add( new SqlParameter() { ParameterName = "@EventoId", SqlValue = id } );
            //        con.Open();
            //        cmd.ExecuteNonQuery();
            //        return "Finalizado com sucesso";
            //    }

            //}
            //catch
            //{
            //    return "Não foi possivel finalizar!";
            //}
        }
    }
}

PROJETO/Agenda/Agenda/Views/Shared/_EventoAberto.cshtml
@model Agenda.Models.Evento

<style rel="stylesheet" type="text/css">
    .tudo {
        display: table;
    }

    .nome {
        float: left;
        width: 15%;
    }

    .dados {
        margin-left: 20%;
    }
</style>
<div class="tudo table table-responsive  " style="border-bottom:medium;border-color:black">
    <div class="nome ">
        <h4 style="color:darkslategrey">@Html.DisplayTextFor(m => m.EventoNome)</h4>
    </div>
    <div class="dados">
        @Html.DisplayTextFor(m => m.EventoDataInicio) até @Html.DisplayTextFor( m => m.EventoDataFim ) <br/>
        @Html.DisplayTextFor( m => m.EventoDescricao) <br />
        <input class="btn btn-default" type="submit" name="btnFinalizar" id="btnFinalizar" value="Feito!" onclick="finalizar(@Model.EventoId);"/>
    </div>
</div>
<hr />

PROJETO/Agenda/Agenda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.2.1.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink( "Categorias", "Index", "Categoria" )</li>
                        <li>@Html.ActionLink( "Eventos", "Index", "Evento" )</li>
                    </ul>
                </button>
                @Html.ActionLink( "Agenda", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" } )
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink( "Categorias", "Index", "Categoria" )</li>
                    <li>@Html.ActionLink( "Eventos", "Index", "Evento" )</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br /><br /><br /><br />
        @RenderBody()
        <hr />
        <footer>
            <center><p>&copy; @DateTime.Now.Year - Agenda  </p></center>
        </footer>
    </div>

    <link href="@Url.Content("~/bundles/jquery")" rel="stylesheet" type="text/javascript" />
    <link href="@Url.Content("~/bundles/bootstrap")" rel="stylesheet" type="text/css" />
        @RenderSection( "scripts", required: false )
</body>
</html>